<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContinueButton</name>
   <tag></tag>
   <elementGuidId>d95388a9-b2cf-4559-8290-e3c8ef4f886d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='a-button-input']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
