<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passwordSignin</name>
   <tag></tag>
   <elementGuidId>4ec038bf-c076-49af-9c23-5226bd02aeeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[id='auth-signin-button']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[id='auth-signin-button']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
