<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Blue</name>
   <tag></tag>
   <elementGuidId>3ade4ef4-7082-4a0f-84b8-6d1d5d23b3fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sw-all-product-variations']/ul/li/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>431c3d1d-4c1c-4897-afcd-562ddbf89fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-base</value>
      <webElementGuid>c204b29f-7068-43cf-bd3f-9414aa428281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Blue
                    </value>
      <webElementGuid>11dcef3d-68cb-41d0-9892-d7ad094800bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sw-all-product-variations&quot;)/ul[@class=&quot;a-unordered-list a-nostyle a-vertical&quot;]/li[@class=&quot;sw-product-variation&quot;]/span[@class=&quot;a-list-item&quot;]/span[@class=&quot;a-size-base&quot;]</value>
      <webElementGuid>c633ae06-2cfa-459e-89a2-580b3f50d5b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sw-all-product-variations']/ul/li/span/span[2]</value>
      <webElementGuid>a6b1307a-7bfa-4fde-9fbf-c0e777d30e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Colour:'])[1]/following::span[1]</value>
      <webElementGuid>7ae38789-1fc8-4cf1-9aee-a119a065265c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Added to Cart'])[1]/following::span[3]</value>
      <webElementGuid>5f5cc71a-ce65-4cc4-b9c7-e969b7b1cb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size:'])[1]/preceding::span[1]</value>
      <webElementGuid>4ad8c54b-42a9-476c-976d-60cb49648a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Style Name:'])[1]/preceding::span[4]</value>
      <webElementGuid>3223c8b5-cf9e-4f17-b084-451cf92e3c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blue']/parent::*</value>
      <webElementGuid>68a36b1e-949b-4886-9005-7bd77b3350cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span/span[2]</value>
      <webElementGuid>82b4b8fe-33e2-4afe-8d82-83d3c2ed25f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                        Blue
                    ' or . = '
                        Blue
                    ')]</value>
      <webElementGuid>565dab5c-4366-48bb-b091-6257d3d0eeb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
