<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pastel</name>
   <tag></tag>
   <elementGuidId>a45469ee-7a3e-403a-b8df-f03ca05abdb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sw-all-product-variations']/ul/li[3]/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>584ff38c-6d26-4501-b41c-fcf2c5894bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-base</value>
      <webElementGuid>109fb392-f970-4f95-86af-7e7fdba0fb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Pastel
                    </value>
      <webElementGuid>743f8b10-3e20-49f9-a7fe-3368a16a61e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sw-all-product-variations&quot;)/ul[@class=&quot;a-unordered-list a-nostyle a-vertical&quot;]/li[@class=&quot;sw-product-variation&quot;]/span[@class=&quot;a-list-item&quot;]/span[@class=&quot;a-size-base&quot;]</value>
      <webElementGuid>082bfa90-5bd2-463a-a013-4594bb1eb5fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sw-all-product-variations']/ul/li[3]/span/span[2]</value>
      <webElementGuid>ba4c3949-2ee0-4575-907e-f238826e553e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Style Name:'])[1]/following::span[1]</value>
      <webElementGuid>e741b3ab-0f6e-4f1b-8c7b-662e717cb3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size:'])[1]/following::span[4]</value>
      <webElementGuid>558d5507-3579-4b6a-a13e-34606a15063b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pattern Name:'])[1]/preceding::span[1]</value>
      <webElementGuid>42c0fbb5-17ce-445a-8868-8d01eaf075c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ball Pen'])[1]/preceding::span[2]</value>
      <webElementGuid>f1b0ccca-d9b8-4d92-8350-30d3c7f38003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pastel']/parent::*</value>
      <webElementGuid>c1b2645e-7850-452e-a6da-3ad2e3362b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span/span[2]</value>
      <webElementGuid>277dd645-43a4-4480-bb8f-24aa0f24e109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                        Pastel
                    ' or . = '
                        Pastel
                    ')]</value>
      <webElementGuid>b9578bfe-83d4-4ae6-a754-bebc1c501439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
