<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Brand__24_Dny</name>
   <tag></tag>
   <elementGuidId>ac42b913-1c42-4693-880c-3bede0bffe7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._24_Dny</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[3]/div[2]/div/div[2]/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2bb0efae-9cd1-47f1-98e8-13ef32c41312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_24_Dny</value>
      <webElementGuid>91c34f5b-80df-4586-985a-0b0a5687ec44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_36fx1h _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg col-2-12&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg col-12-12&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_1KOcBL&quot;]/section[@class=&quot;_167Mu3 _2hbLCH&quot;]/div[@class=&quot;_3FPh42&quot;]/div[@class=&quot;_2d0we9&quot;]/div[@class=&quot;_4921Z t0pPfW&quot;]/div[@class=&quot;_1Y4Vhm _4FO7b6&quot;]/label[@class=&quot;_2iDkf8 t0pPfW&quot;]/div[@class=&quot;_24_Dny&quot;]</value>
      <webElementGuid>318b880a-3a0a-498c-b8c3-2a219cfa0e65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div/div/div/div/section[3]/div[2]/div/div[2]/div/label/div</value>
      <webElementGuid>7568ae6b-9421-4606-8e28-4c0de894fd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>1df8e59b-5cb8-4edf-ad6f-1ab46ced4117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
