<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Newest First__24_Dny</name>
   <tag></tag>
   <elementGuidId>7715c31b-7c4b-49bc-ba0a-b14aebb286a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.f3A4_V > label._2iDkf8 > div._24_Dny</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/div/a/div[2]/div[2]/div/span/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9dcabd1a-70dc-4bab-ad2b-305aa431a627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_24_Dny</value>
      <webElementGuid>f9a28101-f87a-43a7-82e9-28aee720f826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_36fx1h _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_13oc-S&quot;]/div[1]/div[@class=&quot;_2kHMtA&quot;]/a[@class=&quot;_1fQZEK&quot;]/div[@class=&quot;MIXNux&quot;]/div[@class=&quot;_3wLduG&quot;]/div[@class=&quot;_3PzNI-&quot;]/span[@class=&quot;f3A4_V&quot;]/label[@class=&quot;_2iDkf8&quot;]/div[@class=&quot;_24_Dny&quot;]</value>
      <webElementGuid>a20fc808-01e9-47c1-be82-83fe45596dea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/div/a/div[2]/div[2]/div/span/label/div</value>
      <webElementGuid>8123cf24-b69c-4fb9-9d48-cd07db5ef660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label/div</value>
      <webElementGuid>76bc06f9-4360-494e-8b74-4d86b60d620b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
